export const SET_USER_CREDENTIALS = 'SET_USER_CREDENTIALS';
export const SET_IS_NEW_USER = 'SET_IS_NEW_USER';
export const SETH_AUTH_STATUS = 'SETH_AUTH_STATUS';
export const ON_LOGOUT = 'ON_LOGOUT';
